### ISSUE TITLE
platform_hardware_drivers/storage_sd_card doesn't work...

### ISSUE THREAD

**Issue by ApplicationNinja** [SiliconLabs/platform_hardware_drivers#10]
I've tried this exact demo example, and it doesn't work, f_getfree fails within app_init with a return code of 3 ( FR_NOT_READY ).

I have tested the Mikroe SD card click on another processor, the ESP32, and all works fine there, so I know it's not the click board, or SD card.

I am using Gecko SDK 4.1.3 or 4.2.0, both fail.

I am running the example as is, no code changes at all, just importing the .sls and running.

Thoughts?

**Comment by silabs-HopN** [comment]
Hi @ApplicationNinja ,
Thanks for your feedback!
I have checked and found that the problem comes from not having a pull-up resistor on the MISO pin of misroSD click board as shown below.
![image](https://user-images.githubusercontent.com/76993461/215780099-d1c05c04-75bd-48d8-aada-1521d720e690.png)

You know, the MISO input of a processor will be driven by a tri-stated totem pole output from the SDcard. Therefore, a pull-up (e.g., 100k) should be placed on the MISO at least to hold that input into a known state when the SDcard is not selected.
To solve this problem, you should reconfigure the MISO pin in gpioModeInputPull mode by adding the following lines to the **sdc_platform_spi_init()** function (in the **sl_sdc_platform_spi.c** file)
```c
  GPIO_PinModeSet(gpioPortC, 1, gpioModeInputPull, 1);
```
Or you can also download the attachment below, extract and import the sls file. In this example, fatfs libs is updated to R15 version and exFAT is enabled by default as well.
Please check and let me know if you have any problems.
Thanks.
[sdcard_fatfs_r15.zip](https://github.com/SiliconLabs/platform_hardware_drivers/files/10546767/sdcard_fatfs_r15.zip)

**Comment by ApplicationNinja** [comment]
Thank you for your attention to this, I'll test it as soon as I can. But you can close this for now.
